version: "3.8"

services:
  # api:
  #   build: .
  #   command: uvicorn APIendpoint:app --host 0.0.0.0 --port 8000 --reload
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - USER_UPLOADS_DIR=/app/uploads

  web:
    build: .
    command: reflex run --host 0.0.0.0 --port 3000 --no-browser
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - api